### ISSUE TITLE
[::1]:5432: connect error

### ISSUE THREAD

**Issue by Ext7** [moneropay/moneropay#1]
Hi.
Built image from Dockerfile. Tried to run container from it but constantly receive this error: 

_Unable to connect to database: failed to connect to `host=localhost user=moneropay database=moneropay`: dial error (dial tcp [::1]:5432: connect: cannot assign requested address)_

Also container exits immediately even with -d, -dt or -dit options.

Any ideas how to fix it?

**Comment by sausagenoods** [comment]
It seems like the database you're running on localhost:5432 is not accessible within the container. If the database isn't inside another container can you try setting the environment variable `POSTGRES_HOST=host.docker.internal` or passing the argument `--postgres-host=host.docker.internal` to MoneroPay and try again?

**Comment by Ext7** [comment]
1. Made `export POSTGRES_HOST=host.docker.internal ` through CLI
2. Then `docker run -dit --name monero moneropay:1.0 `

Recieved the same error
`docker logs monero`
_Unable to connect to database: failed to connect to `host=localhost user=moneropay database=moneropay`: dial error (dial tcp [::1]:5432: connect: cannot assign requested address)_

This postgre DB must run in container or I need to run it separately on host machine? Readme doesn't specify this moments.

**Comment by Ext7** [comment]
Maybe my build command was wrong? Here is it's output:

`docker build -t moneropay:1.0 .`

Sending build context to Docker daemon  292.9kB
Step 1/12 : FROM golang:alpine as builder
alpine: Pulling from library/golang
59bf1c3509f3: Pull complete                                                                                   
666ba61612fd: Pull complete                                                                                   
8ed8ca486205: Pull complete                                                                                   
bfe7d510f522: Pull complete                                                                                   
560f678454b3: Pull complete                                                                                   
Digest: sha256:a207b29286084e7342286de809756f61558b00b81f794406399027631e0dba8b
Status: Downloaded newer image for golang:alpine
 ---> 861f73fe2c7f
Step 2/12 : WORKDIR /build
 ---> Running in 6e2a5f3590b4
Removing intermediate container 6e2a5f3590b4
 ---> e8bc5e8928f4
Step 3/12 : COPY go.mod go.sum ./
 ---> 617dc73e3e9f
Step 4/12 : RUN go mod download -x
 ---> Running in 96e73df593ff
`# get https://proxy.golang.org/golang.org/x/crypto/@v/v0.0.0-20210711020723-a769d52b0f97.mod`
`# get https://proxy.golang.org/github.com/gabstv/httpdigest/@v/v0.0.0-20200601123255-912d52c2d608.mod`
...
...
Removing intermediate container 96e73df593ff
 ---> 6fe27004f78b
Step 5/12 : COPY . .
 ---> 0e8270a88b3b
Step 6/12 : ENV CGO_ENABLED=0
 ---> Running in 3ac0a71f674b
Removing intermediate container 3ac0a71f674b
 ---> 036c4dfe7b3a
Step 7/12 : RUN go build        cmd/moneropayd/moneropayd.go
 ---> Running in 2cae2f3b1c04
Removing intermediate container 2cae2f3b1c04
 ---> 5d3a3917ac83
Step 8/12 : FROM scratch
 ---> 
Step 9/12 : COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
 ---> 467ef56c53ea
Step 10/12 : WORKDIR /app
 ---> Running in 604d31137360
Removing intermediate container 604d31137360
 ---> d5a681105bec
Step 11/12 : COPY --from=builder /build/moneropayd .
 ---> 430588e2efd1
Step 12/12 : CMD ["./moneropayd", "-bind=:5000"]
 ---> Running in 767827840ae4
Removing intermediate container 767827840ae4
 ---> d77d69d83df9
Successfully built d77d69d83df9
Successfully tagged moneropay:1.0

**Comment by sausagenoods** [comment]
You must use the `-e` or `--env` in your docker command to pass environment variables to your container. The database can be run inside of a container or on the host machine.

If your database is running on the host, this command should make your database accesible to the container:
`docker run -dit --net=host --name monero moneropay:1.0`

If your database is inside a container, see:
https://docs.docker.com/network/
If this is the case I suggest running both MoneroPay and Postgresql under docker-compose. docker-compose by default will join them to the default network and assign them hostnames identical to the container names. https://docs.docker.com/compose/networking/

These things aren't in the readme because rather than MoneroPay, this is how Docker works.

**Comment by Ext7** [comment]
Thank you, will try your solution later. 
I mean it's not clear for me that separate postgre must be prepared and run - I thought it is included in moneropay docker.

Could you please clarify then some moments in readme? 
Blocks about api calls are clear enough. But "usage" block is too laconic :)

What means this block?

```
$ ./moneropayd -h
Usage of ./moneropayd:
  -bind="localhost:5000": Bind address:port for moneropayd
...
...
```

They are already present in config.go file but I must use them somewhere else? 

And this block:

```
#!/bin/sh
export RPC_ADDRESS='http://localhost:18083/json_rpc'
export RPC_USERNAME='kernal'
export RPC_PASSWORD='s3cure'
export POSTGRES_PASSWORD='s3cure'
./moneropayd
```

Need to save in to .sh file and run?

**Comment by Ext7** [comment]
Fixed issue with postgre. Just installing it locally and creating user and database isn't enough - it leads to error:
_Unable to connect to database: failed to connect to `host=localhost user=moneropay database=moneropay`: failed SASL auth (expected AuthenticationSASLFinal message but received unexpected message)_

Need to change string in /etc/postgresql/14/main/pg_hba.conf 
from
_local   all             all                                     peer_ 
to
_local   all             all                                     trust_
to fix it.

But after starting moneropay container another issue arise: 

**_Post "http://localhost:18082/json_rpc": dial tcp 127.0.0.1:18082: connect: connection refused_**

Opening http://localhost:18082/json_rpc in browser shows  _"This site can’t be reached"_
While  http://localhost:5000 gives _"404 page not found"_

Need to install and start rpc-server somehow? Or change some configs?

**Comment by sausagenoods** [comment]
You need to connect to a wallet rpc server instance. It's noted in the command line parameters required to run MoneroPay. If you were to read the Dockerfile you would also see that we don't provide a database and wallet rpc inside the same container as MoneroPay. We will be providing a docker-compose file in the near future.

Also please note that this repository is a mirror and we handle issues on gitlab. I will be closing this issue because this thread is not related to MoneroPay and here is not the correct place. You can join our Matrix chat if you have any further questions: https://matrix.to/#/!rAfWWYzxDWYRlAxObk:kernal.eu?via=kernal.eu&via=matrix.org&via=monero.social
